### ISSUE TITLE
Exito no código 

### ISSUE THREAD

**Issue by dnloliveira1** [amandafilizola/ex6b-grupo04#7]
o código está compilando apos muito estudo e raça deu certo
agradecer a Artur que ajudou na dica 6 (reduzindo o tempo de montá-lo)
e tbm agradecer, principalmente, a amanda, que deu todo apoio no git, e no código como um todo
:+1:  

o seu tempo de compilação é entre 10min - 15 min

**Comment by amandafilizola** [comment]
YAASS!! :D
